global:
  checknewversion: true

api:
  dashboard: true
  insecure: false
  debug: true

log:
  level: DEBUG
  filepath: "/etc/traefik/log/traefik.log"

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure

  websecure:
    address: :443
    http:
      middlewares:
        - secureHeaders@file
      tls:
        certResolver: letsencrypt

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: 
  file:
    filename: /configurations/dynamic.yml

certificatesResolvers:
  letsencrypt:
    acme:
      email: 
      storage: /letsencrypt/acme.json
      keyType: EC384
      httpChallenge:
        entryPoint: web